Written by. Gukhwan Hyun

# Backpropagation (hard coding)

In [ ]:
import torch.nn.functional as F
import torch

In [ ]:
input = torch.FloatTensor([0.0, 1.0])
w1 = 3.34
b1 = -1.43
w2 = -3.53
b2 = 0.57
b3= 0
 
y1 = F.softplus(input*w1+b1)
y2 = F.softplus(input*w2+b2)
w3 = -1.22 
w4 = -2.30

predicted = y1 * w3 +  y2* w4 + b3

predicted

tensor([-2.6037, -2.6149])

In [ ]:
# predicted value for an input
predicted[0].item()

-2.6036651134490967

In [ ]:
# loss for an input
-2*(0 - predicted[0].item())

-5.207330226898193

In [ ]:
# SSR or slope
slope = sum([-2*(0 - predicted[0].item())])
slope

-5.207330226898193

In [ ]:
# Gradient Descent
learning_rate = 0.1
step_size = slope * learning_rate
b3 = b3 - step_size
b3

1.2437069416046143

In [ ]:
# Entire process of Gradient descent
input = torch.FloatTensor([0.0, 0.5, 1.0])
w1 = 3.34
b1 = -1.43
w2 = -3.53
b2 = 0.57
b3= 0
 
y1 = F.softplus(input*w1+b1)
y2 = F.softplus(input*w2+b2)
w3 = -1.22 
w4 = -2.30
observed = [0,1,0]

for i in range(15):  # 15 = num of steps
  print('observed = ',observed)
  predicted = y1 * w3 +  y2* w4 + b3

  print('predicted = ',predicted)

  slope = sum([-2*(observed[0] - predicted[0].item()),
               -2*(observed[1] - predicted[1].item()),
               -2*(observed[2] - predicted[2].item())])
  print('slope', slope)

  learning_rate = 0.1
  step_size = slope * learning_rate
  b3 = b3 - step_size
  print('step_size', step_size)
  print('new b3 =', b3)
  print('-'*100)

observed =  [0, 1, 0]
predicted =  tensor([-2.6037, -1.6090, -2.6149])
slope -15.655108213424683
step_size -1.5655108213424684
new b3 = 1.5655108213424684
----------------------------------------------------------------------------------------------------
observed =  [0, 1, 0]
predicted =  tensor([-1.0382, -0.0435, -1.0494])
slope -6.262042999267578
step_size -0.6262042999267579
new b3 = 2.191715121269226
----------------------------------------------------------------------------------------------------
observed =  [0, 1, 0]
predicted =  tensor([-0.4119,  0.5827, -0.4232])
slope -2.504816770553589
step_size -0.2504816770553589
new b3 = 2.442196798324585
----------------------------------------------------------------------------------------------------
observed =  [0, 1, 0]
predicted =  tensor([-0.1615,  0.8332, -0.1727])
slope -1.001927137374878
step_size -0.1001927137374878
new b3 = 2.5423895120620728
----------------------------------------------------------------------------------

# Backpropagation (torch)

In [ ]:
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
import torch

In [ ]:
class Torch_Net(nn.Module):
  def __init__(self):
    super(Torch_Net, self).__init__()
    self.fc1 = nn.Linear(1, 2)
    self.fc2 = nn.Linear(2,1)

  def forward(self, x):
    x = F.softplus(self.fc1(x))
    x = self.fc2(x)
    return x

In [ ]:
input = torch.FloatTensor([[0],  
                          [0.5],  
                          [1]]).requires_grad_()
observed = torch.Tensor([[0],
                        [1],
                        [0]])

model = Torch_Net()

optimizer = optim.SGD(model.parameters(), lr=0.1)

for i in range(1,3000):
  pred = model(input)
  loss = F.mse_loss(pred, observed, reduction='sum')
  optimizer.zero_grad() 
  loss.backward() 
  optimizer.step()

  print('pred', pred)
  print("weights, biases", list(model.parameters()))
  print('loss', loss.item())
  print('-' * 50 + f'step_{i}' + '-' * 50)
  print()

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
tensor([[-1.6066],
        [-4.6167]], requires_grad=True), Parameter containing:
tensor([0.8935, 0.2364], requires_grad=True), Parameter containing:
tensor([[ 1.9942, -2.3077]], requires_grad=True), Parameter containing:
tensor([-0.5033], requires_grad=True)]
loss 0.16897457838058472
--------------------------------------------------step_2583--------------------------------------------------

pred tensor([[0.0742],
        [0.6972],
        [0.2634]], grad_fn=<AddmmBackward0>)
weights, biases [Parameter containing:
tensor([[-1.6096],
        [-4.6230]], requires_grad=True), Parameter containing:
tensor([0.9011, 0.2414], requires_grad=True), Parameter containing:
tensor([[ 1.9996, -2.3133]], requires_grad=True), Parameter containing:
tensor([-0.5103], requires_grad=True)]
loss 0.1665637195110321
--------------------------------------------------step_2584--------------------------------------------------

pred tensor([[0.0736],
        [0.6995],
     

In [ ]:
new_var =  torch.FloatTensor([0]) 
model(new_var)

tensor([0.1398], grad_fn=<AddBackward0>)

In [ ]:
new_var =  torch.FloatTensor([0.5]) 
model(new_var)

tensor([0.6597], grad_fn=<AddBackward0>)