**3.1.1 텐서의 차원 자유자재로 다루기**

In [ ]:
# Pytorch 임포트
import torch

In [ ]:
# pytorch에서 가장 기본적인 자료 구조 tensor 만들기
# 가로, 세로 2차원으로만 이뤄진 랭크 2 텐서
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# 텐서의 형태는 size() 함수 또는 shape을 사용해 각 차원의 크기 확인
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [ ]:
# 랭크 늘리기 : unsqueeze()
x = torch.unsqueeze(x, 0)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [ ]:
# 랭크 줄이기 : squeeze()
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [ ]:
# 텐서 모양 바꾸기 : view()
x = x.view(9)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
랭크(차원): 1


In [ ]:
# view() 함수로 x의 모양을 [2,4]로 시도
# 원소가 9개인 텐서를 원소가 8개(2x4)인 텐서로 바꿀 수 없음
try:
  x = x.view(2,4)
except Exception as e:
  print(e) # 에러 출력

shape '[2, 4]' is invalid for input of size 9
