**unsqueeze() 함수**

In [1]:
import torch 

In [4]:
# tensor 구조 : (채널, 높이, 넓이)
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [5]:
# x라는 텐서의 0(채널) 1 늘리기
x = torch.unsqueeze(x, 0)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [ ]:
# x라는 텐서의 1(높이)) 1 늘리기
x = torch.unsqueeze(x, 1)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
Shape: torch.Size([3, 1, 3])
랭크(차원): 3


In [ ]:
# x라는 텐서의 2(넓이) 1 늘리기
x = torch.unsqueeze(x, 2)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
Shape: torch.Size([3, 3, 1])
랭크(차원): 3


In [ ]:
# 3차원에서 4차원으로 늘리기
x = torch.unsqueeze(x, 3)  # 4번째 인덱스
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[[1]],

         [[2]],

         [[3]]],


        [[[4]],

         [[5]],

         [[6]]],


        [[[7]],

         [[8]],

         [[9]]]])
Shape: torch.Size([3, 3, 1, 1])
랭크(차원): 4


**squeeze() 함수**

In [ ]:
# squeeze() 함수는 크기가 1인 차원을 지움
x = torch.squeeze(x) # 인덱스를 지정하지 않고 squeeze()를 실행하면 크기가 1인 차원을 모두 지움
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [ ]:
# 텐서의 0(채널)에 크기가 1인 차원 다시 늘리기
x = torch.unsqueeze(x, 0)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [ ]:
# 텐서의 4번째에 크기가 1인 차원 더 늘리기
x = torch.unsqueeze(x, 3)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[[1],
          [2],
          [3]],

         [[4],
          [5],
          [6]],

         [[7],
          [8],
          [9]]]])
Shape: torch.Size([1, 3, 3, 1])
랭크(차원): 4


In [ ]:
# 삭제하고자 하는 인덱스를 직접 지정해주어 차원 줄이기 
x = torch.squeeze(x, 3) # 4번째 인덱스 지정
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


**view() 함수**

In [6]:
# 2x3 모양의 텐서
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
랭크(차원): 2


In [12]:
# 3x2 모양의 텐서로 바꾸기
x = x.view(3, 2) # x.view(가로, 세로)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])
랭크(차원): 2


In [ ]:
# 인수 값에 1을 추가하여 차원을 늘려서 텐서의 모양을 바꿀 수 있음
# 단, 텐서의 원소가 6이므로 3x2x1=6 이어야 함
x = x.view(3, 2, 1)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
Shape: torch.Size([3, 2, 1])
랭크(차원): 3


In [ ]:
# 한 줄의 텐서 모양
x = x.view(6)
print(x)
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([1, 2, 3, 4, 5, 6])
Shape: torch.Size([6])
랭크(차원): 1
